export interface EngineHandshake {
  port: number;
  token: string;
}

export type LLMProvider = 'openai' | 'anthropic' | 'openrouter' | 'gemini';

/**
 * Auth shape on the WS start frame. Discriminated union so the engine
 * never has to guess whether `api_key` carries an API key or an OAuth
 * access token. OAuth is OpenAI-only today.
 */
export type ProviderAuth =
  | { type: 'api_key'; api_key: string }
  | { type: 'oauth'; access: string; refresh: string; expires: number };

export interface ProviderConfig {
  provider: LLMProvider;
  auth: ProviderAuth;
  model?: string;
  max_tokens?: number;
}

/** Canonical UI labels for each provider. Used in status cards + transcripts. */
export const PROVIDER_LABEL: Record<LLMProvider, string> = {
  openai: 'OpenAI',
  anthropic: 'Anthropic',
  openrouter: 'OpenRouter',
  gemini: 'Google Gemini',
};

/** Default model the engine assumes when ProviderConfig.model is not set. */
export const PROVIDER_DEFAULT_MODEL: Record<LLMProvider, string> = {
  openai: 'gpt-4o-mini',
  anthropic: 'claude-haiku-4-5',
  openrouter: 'openai/gpt-4o-mini',
  gemini: 'gemini-2.0-flash',
};

/**
 * Priority order when multiple keys are configured. First match wins.
 * Reordering here changes which provider runs the live debate; the
 * renderer surfaces the chosen one in the Analyze status card.
 */
export const PROVIDER_PRIORITY: readonly LLMProvider[] = [
  'openai',
  'anthropic',
  'openrouter',
  'gemini',
];

export const PROVIDER_SECRET_KEY: Record<LLMProvider, string> = {
  openai: 'llm:openai',
  anthropic: 'llm:anthropic',
  openrouter: 'llm:openrouter',
  gemini: 'llm:gemini',
};

export interface AnalyzeRequest {
  ticker: string;
  trade_date: string;
  provider_config?: ProviderConfig;
}

export interface AnalyzeDecision {
  action: 'BUY' | 'SELL' | 'HOLD' | string;
  confidence: number;
  reasoning: string;
}

export interface AnalyzeResponse {
  ok: boolean;
  ticker: string;
  trade_date: string;
  decision: AnalyzeDecision;
  agents: unknown[];
}

export interface SessionCompleteEvent {
  type: 'session.complete';
  ticker: string;
  trade_date: string;
  decision: AnalyzeDecision;
  /** True when the debate was generated by a live LLM. */
  live?: boolean;
  /** Provider id (one of LLMProvider). */
  provider?: LLMProvider;
  /** Model name used for a live debate. */
  model?: string;
  input_tokens?: number;
  output_tokens?: number;
  estimated_cost_usd?: number;
}

export interface QuoteSummary {
  ticker: string;
  trade_date: string;
  as_of: string;
  last_close: number;
  period_open: number;
  period_high: number;
  period_low: number;
  period_change_pct: number;
  avg_volume: number;
  sessions: number;
  source: string;
}

export interface Headline {
  title: string;
  publisher: string;
  pub_date: string;
  url: string;
  summary: string;
}

export interface NewsHeadlinesEvent {
  type: 'news.headlines';
  ticker: string;
  source: string;
  headlines: Headline[];
}

export type DebateEvent =
  | { type: 'session.start'; ticker: string; trade_date: string }
  | ({ type: 'data.summary' } & QuoteSummary)
  | NewsHeadlinesEvent
  | { type: 'agent.message'; agent: string; phase: string; content: string }
  | { type: 'phase.transition'; from: string; to: string }
  | SessionCompleteEvent;

export interface StreamHandle {
  close(): void;
  done: Promise<void>;
}

let cachedHandshake: EngineHandshake | null = null;

async function handshake(): Promise<EngineHandshake> {
  if (cachedHandshake) return cachedHandshake;
  if (!window.tradingAgentsLab?.getEngineHandshake) {
    throw new Error('engine bridge not available — preload not loaded');
  }
  const result = await window.tradingAgentsLab.getEngineHandshake();
  cachedHandshake = result;
  return result;
}

export async function getHandshake(): Promise<EngineHandshake> {
  return handshake();
}

export interface HealthInfo {
  ok: boolean;
  version: string;
  uptime_seconds: number;
  engine_state: string;
  data_provider?: string;
  live_supported?: boolean;
  live_default_model?: string;
  storage_path?: string;
}

export interface SessionSummary {
  id: string;
  ticker: string;
  trade_date: string;
  decision_action: string;
  decision_confidence: number;
  decision_reasoning: string;
  live: boolean;
  provider: string | null;
  model: string | null;
  input_tokens: number | null;
  output_tokens: number | null;
  estimated_cost_usd: number | null;
  created_at: string;
}

export interface SessionDetail extends SessionSummary {
  events: DebateEvent[];
}

export async function getHealth(): Promise<HealthInfo> {
  const { port, token } = await handshake();
  const res = await fetch(`http://127.0.0.1:${port}/health`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    throw new Error(`/health failed: ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as HealthInfo;
}

export async function listSessions(opts: { limit?: number; ticker?: string } = {}): Promise<SessionSummary[]> {
  const { port, token } = await handshake();
  const params = new URLSearchParams();
  if (opts.limit) params.set('limit', String(opts.limit));
  if (opts.ticker) params.set('ticker', opts.ticker);
  const qs = params.toString();
  const url = `http://127.0.0.1:${port}/sessions${qs ? `?${qs}` : ''}`;
  const res = await fetch(url, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    throw new Error(`listSessions failed: ${res.status} ${res.statusText}`);
  }
  const body = (await res.json()) as { sessions: SessionSummary[] };
  return body.sessions;
}

export async function getSession(id: string): Promise<SessionDetail> {
  const { port, token } = await handshake();
  const res = await fetch(
    `http://127.0.0.1:${port}/sessions/${encodeURIComponent(id)}`,
    { headers: { Authorization: `Bearer ${token}` } },
  );
  if (!res.ok) {
    throw new Error(`getSession failed: ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as SessionDetail;
}

export async function deleteSession(id: string): Promise<void> {
  const { port, token } = await handshake();
  const res = await fetch(
    `http://127.0.0.1:${port}/sessions/${encodeURIComponent(id)}`,
    {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    },
  );
  if (!res.ok) {
    throw new Error(`deleteSession failed: ${res.status} ${res.statusText}`);
  }
}

export interface WatchlistEntry {
  ticker: string;
  added_at: string;
  note: string | null;
}

export async function listWatchlist(): Promise<WatchlistEntry[]> {
  const { port, token } = await handshake();
  const res = await fetch(`http://127.0.0.1:${port}/watchlist`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    throw new Error(`listWatchlist failed: ${res.status} ${res.statusText}`);
  }
  const body = (await res.json()) as { watchlist: WatchlistEntry[] };
  return body.watchlist;
}

export async function addWatchlist(input: {
  ticker: string;
  note?: string;
}): Promise<WatchlistEntry> {
  const { port, token } = await handshake();
  const res = await fetch(`http://127.0.0.1:${port}/watchlist`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ ticker: input.ticker, note: input.note ?? null }),
  });
  if (!res.ok) {
    if (res.status === 409) {
      throw new Error(`${input.ticker} is already on the watchlist`);
    }
    if (res.status === 400 || res.status === 422) {
      throw new Error(`Invalid ticker: ${input.ticker}`);
    }
    throw new Error(`addWatchlist failed: ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as WatchlistEntry;
}

export async function removeWatchlist(ticker: string): Promise<void> {
  const { port, token } = await handshake();
  const res = await fetch(
    `http://127.0.0.1:${port}/watchlist/${encodeURIComponent(ticker)}`,
    {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    },
  );
  if (!res.ok) {
    throw new Error(`removeWatchlist failed: ${res.status} ${res.statusText}`);
  }
}

export async function analyze(req: AnalyzeRequest): Promise<AnalyzeResponse> {
  const { port, token } = await handshake();
  const res = await fetch(`http://127.0.0.1:${port}/analyze`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(req),
  });
  if (!res.ok) {
    throw new Error(`analyze failed: ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as AnalyzeResponse;
}

export async function streamDebate(
  req: AnalyzeRequest,
  onEvent: (event: DebateEvent) => void,
  onError?: (err: unknown) => void,
): Promise<StreamHandle> {
  const { port, token } = await handshake();
  const ws = new WebSocket(
    `ws://127.0.0.1:${port}/stream?token=${encodeURIComponent(token)}`,
  );

  let resolveDone: () => void;
  let rejectDone: (err: unknown) => void;
  const done = new Promise<void>((resolve, reject) => {
    resolveDone = resolve;
    rejectDone = reject;
  });

  ws.addEventListener('open', () => {
    // Send the start frame. provider_config is optional — when present, the
    // engine runs a real-LLM debate; when absent, it falls back to the canned
    // stub. Either way the wire shape downstream is the same.
    //
    // The `auth` field is a discriminated union {type: "api_key" | "oauth"}.
    // Engine accepts both the new shape and legacy {api_key: ...} top-level
    // for backward compat with older renderer builds.
    ws.send(
      JSON.stringify({
        ticker: req.ticker,
        trade_date: req.trade_date,
        provider_config: req.provider_config,
      }),
    );
  });

  ws.addEventListener('message', (msg) => {
    try {
      const parsed = JSON.parse(msg.data as string) as DebateEvent;
      onEvent(parsed);
    } catch (err) {
      onError?.(err);
    }
  });

  ws.addEventListener('error', (event) => {
    onError?.(event);
  });

  ws.addEventListener('close', (event) => {
    if (event.code === 1000) {
      resolveDone();
    } else if (event.code === 1005) {
      // 1005 = no status received — treat as clean if server closed before
      // browser saw the close frame. Server explicitly sends 1000, so this
      // path is only hit on edge timing.
      resolveDone();
    } else {
      rejectDone(new Error(`stream closed with code ${event.code}: ${event.reason}`));
    }
  });

  return {
    close: () => {
      if (ws.readyState === WebSocket.OPEN || ws.readyState === WebSocket.CONNECTING) {
        ws.close();
      }
    },
    done,
  };
}
