export interface EngineHandshake {
  port: number;
  token: string;
}

export interface ProviderConfig {
  provider: 'openai';
  api_key: string;
  model?: string;
  max_tokens?: number;
}

export interface AnalyzeRequest {
  ticker: string;
  trade_date: string;
  provider_config?: ProviderConfig;
}

export interface AnalyzeDecision {
  action: 'BUY' | 'SELL' | 'HOLD' | string;
  confidence: number;
  reasoning: string;
}

export interface AnalyzeResponse {
  ok: boolean;
  ticker: string;
  trade_date: string;
  decision: AnalyzeDecision;
  agents: unknown[];
}

export interface SessionCompleteEvent {
  type: 'session.complete';
  ticker: string;
  trade_date: string;
  decision: AnalyzeDecision;
  /** True when the debate was generated by a live LLM. */
  live?: boolean;
  /** Model name used for a live debate. */
  model?: string;
  input_tokens?: number;
  output_tokens?: number;
  estimated_cost_usd?: number;
}

export interface QuoteSummary {
  ticker: string;
  trade_date: string;
  as_of: string;
  last_close: number;
  period_open: number;
  period_high: number;
  period_low: number;
  period_change_pct: number;
  avg_volume: number;
  sessions: number;
  source: string;
}

export interface Headline {
  title: string;
  publisher: string;
  pub_date: string;
  url: string;
  summary: string;
}

export interface NewsHeadlinesEvent {
  type: 'news.headlines';
  ticker: string;
  source: string;
  headlines: Headline[];
}

export type DebateEvent =
  | { type: 'session.start'; ticker: string; trade_date: string }
  | ({ type: 'data.summary' } & QuoteSummary)
  | NewsHeadlinesEvent
  | { type: 'agent.message'; agent: string; phase: string; content: string }
  | { type: 'phase.transition'; from: string; to: string }
  | SessionCompleteEvent;

export interface StreamHandle {
  close(): void;
  done: Promise<void>;
}

let cachedHandshake: EngineHandshake | null = null;

async function handshake(): Promise<EngineHandshake> {
  if (cachedHandshake) return cachedHandshake;
  if (!window.tradingAgentsLab?.getEngineHandshake) {
    throw new Error('engine bridge not available — preload not loaded');
  }
  const result = await window.tradingAgentsLab.getEngineHandshake();
  cachedHandshake = result;
  return result;
}

export async function getHandshake(): Promise<EngineHandshake> {
  return handshake();
}

export interface HealthInfo {
  ok: boolean;
  version: string;
  uptime_seconds: number;
  engine_state: string;
  data_provider?: string;
  live_supported?: boolean;
  live_default_model?: string;
  storage_path?: string;
}

export interface SessionSummary {
  id: string;
  ticker: string;
  trade_date: string;
  decision_action: string;
  decision_confidence: number;
  decision_reasoning: string;
  live: boolean;
  model: string | null;
  input_tokens: number | null;
  output_tokens: number | null;
  estimated_cost_usd: number | null;
  created_at: string;
}

export interface SessionDetail extends SessionSummary {
  events: DebateEvent[];
}

export async function getHealth(): Promise<HealthInfo> {
  const { port, token } = await handshake();
  const res = await fetch(`http://127.0.0.1:${port}/health`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    throw new Error(`/health failed: ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as HealthInfo;
}

export async function listSessions(opts: { limit?: number; ticker?: string } = {}): Promise<SessionSummary[]> {
  const { port, token } = await handshake();
  const params = new URLSearchParams();
  if (opts.limit) params.set('limit', String(opts.limit));
  if (opts.ticker) params.set('ticker', opts.ticker);
  const qs = params.toString();
  const url = `http://127.0.0.1:${port}/sessions${qs ? `?${qs}` : ''}`;
  const res = await fetch(url, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    throw new Error(`listSessions failed: ${res.status} ${res.statusText}`);
  }
  const body = (await res.json()) as { sessions: SessionSummary[] };
  return body.sessions;
}

export async function getSession(id: string): Promise<SessionDetail> {
  const { port, token } = await handshake();
  const res = await fetch(
    `http://127.0.0.1:${port}/sessions/${encodeURIComponent(id)}`,
    { headers: { Authorization: `Bearer ${token}` } },
  );
  if (!res.ok) {
    throw new Error(`getSession failed: ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as SessionDetail;
}

export async function deleteSession(id: string): Promise<void> {
  const { port, token } = await handshake();
  const res = await fetch(
    `http://127.0.0.1:${port}/sessions/${encodeURIComponent(id)}`,
    {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    },
  );
  if (!res.ok) {
    throw new Error(`deleteSession failed: ${res.status} ${res.statusText}`);
  }
}

export async function analyze(req: AnalyzeRequest): Promise<AnalyzeResponse> {
  const { port, token } = await handshake();
  const res = await fetch(`http://127.0.0.1:${port}/analyze`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(req),
  });
  if (!res.ok) {
    throw new Error(`analyze failed: ${res.status} ${res.statusText}`);
  }
  return (await res.json()) as AnalyzeResponse;
}

export async function streamDebate(
  req: AnalyzeRequest,
  onEvent: (event: DebateEvent) => void,
  onError?: (err: unknown) => void,
): Promise<StreamHandle> {
  const { port, token } = await handshake();
  const ws = new WebSocket(
    `ws://127.0.0.1:${port}/stream?token=${encodeURIComponent(token)}`,
  );

  let resolveDone: () => void;
  let rejectDone: (err: unknown) => void;
  const done = new Promise<void>((resolve, reject) => {
    resolveDone = resolve;
    rejectDone = reject;
  });

  ws.addEventListener('open', () => {
    // Send the start frame. provider_config is optional — when present, the
    // engine runs a real-LLM debate; when absent, it falls back to the canned
    // stub. Either way the wire shape downstream is the same.
    ws.send(
      JSON.stringify({
        ticker: req.ticker,
        trade_date: req.trade_date,
        provider_config: req.provider_config,
      }),
    );
  });

  ws.addEventListener('message', (msg) => {
    try {
      const parsed = JSON.parse(msg.data as string) as DebateEvent;
      onEvent(parsed);
    } catch (err) {
      onError?.(err);
    }
  });

  ws.addEventListener('error', (event) => {
    onError?.(event);
  });

  ws.addEventListener('close', (event) => {
    if (event.code === 1000) {
      resolveDone();
    } else if (event.code === 1005) {
      // 1005 = no status received — treat as clean if server closed before
      // browser saw the close frame. Server explicitly sends 1000, so this
      // path is only hit on edge timing.
      resolveDone();
    } else {
      rejectDone(new Error(`stream closed with code ${event.code}: ${event.reason}`));
    }
  });

  return {
    close: () => {
      if (ws.readyState === WebSocket.OPEN || ws.readyState === WebSocket.CONNECTING) {
        ws.close();
      }
    },
    done,
  };
}
